import { Post } from "@prisma/client";
import type { NextPage } from "next";
import Head from "next/head";
import { prismaClient } from "../lib/prismaClient";
import styles from "../styles/Home.module.css";

interface HomeProps {
  posts: Post[];
}

const Home: NextPage<HomeProps> = ({ posts }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {posts.map((post: Post) => (
          <div>
            {post.id} - {post.title}
          </div>
        ))}
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export const getStaticProps = async ({}) => {
  const posts = await prismaClient.post.findMany();

  return {
    props: {
      posts,
    },
  };
};

export default Home;
